# Generated by Django 5.0.7 on 2024-07-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, null=True, unique=True)),
                ('professor', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
