# Generated by Django 5.0.7 on 2024-07-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(unique=True),
        ),
    ]
