# Generated by Django 5.0.7 on 2024-07-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=255, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=255)),
                ('locker_number', models.IntegerField()),
                ('locker_combination', models.CharField(max_length=8)),
                ('good_student', models.BooleanField(default=True)),
            ],
        ),
    ]
