# Generated by Django 5.0.7 on 2024-07-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_alter_student_locker_combination'),
        ('subject_app', '0003_alter_subject_professor_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='subject_app.subject'),
        ),
    ]
